variables:
  repo: gitlab.thevirtualbrain.org:5000
  tag: tvb/pipeline

build:
  stage: build
  tags:
    - hipwork
  script:
    - docker build -t $repo/$tag:$CI_COMMIT_REF_NAME .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $repo
    - docker push $repo/$tag/$CI_COMMIT_REF_NAME

