#!/bin/bash

if docker info &> /dev/null
then
    docker="docker "
else
    docker="sudo docker "
fi

data_path=${TVB_MAKE_DATA:-"$(pwd)/data"}
data_mapping="-v $data_path:/opt/tvb-make/data"

if $docker info &> /dev/null
then
    echo $docker run --rm -it $data_mapping maedoc/tvb-make $@
else
    echo "unable to access Docker, is it running?"
    exit 1
fi

