#!/bin/bash

function getValue {
    kw=$1
    for str in ${@:2}
    do
        IFS='=' read -a pair <<< "$str"
        if [ "${pair[0]}" == "SUBJECT" ]; then
           echo ${pair[1]}
           return
        fi
    done
}

function runSubject {
    args=$*

    # Commented ?
    if [[ $args =~ [:space:]*\#.* ]]
    then
        return
    fi

    subject=`getValue SUBJECT $args`
    if [[ -z $subject ]]
    then
        echo "Missing SUBJECT"
        return 1
    fi

    mkdir -p $subjects_dir/_logs
    outfile=$subjects_dir/_logs/${subject}.%j.stdout
    errfile=$subjects_dir/_logs/${subject}.%j.stderr

    $submit_cmd -o $outfile -e $errfile $run_one_path $args
}


# abs path to cluster/run-one script, regardless of
# working directory of invocation
run_one_path=$(cd $(dirname $0) && pwd)/run-one

# Submit using SLURM
submit_cmd="srun -N 1 -n 1"

# We have to pass the environment variables explicitely
if [[ ! -z $SUBJECTS_DIR ]]
then
    submit_cmd="${submit_cmd} --export=SUBJECTS_DIR=${SUBJECTS_DIR}"
fi

subjects_dir=${SUBJECTS_DIR:-$(pwd)/fs}

if [ "$#" -ne 1 ]
then
    runSubject $@
else
    while read LINE
    do
        runSubject $LINE
    done < $1
fi
